:toc:
:toc-placement!:

++++
<h1 align="center"><em>THESIS TITLE</em></h1>
<h4 align="center">Bachelor's Degree in Computer Science</h4>

<p align="center">
    Andrea Esposito (677021)<br>
    <small>Author</small><br>
    <a href="mailto:a.esposito39@studenti.uniba.it">a.esposito39@studenti.uniba.it</a>
</p>
<p align="center">
    Prof. Giuseppe Desolda<br>
    Supervisor<br>
    <a href="mailto:giuseppe.desolda@uniba.it">giuseppe.desolda@uniba.it</a>
</p>
++++

toc::[]

* * *
        
== The Structure of the Repository

`browser-extension/`:: This folder contains the source code for the browser
extension.

`thesis/`:: This folder contains the thesis itself.

`thesis/src/`::: This folder contains the source code (LaTeX) of the document.

`thesis/out/`::: This folder contains the final PDF builded by running the
command `make dist`

== The Browser Extension

A simple browser extension was created to collect data for the Thesis' research.
The plugin is available for both Google Chrome and Mozilla Firefox.

The extension has the single goal of collecting the data that will be analyzed
in the Thesis. A detailed list of what is collected can be found in
<<data-collection-data-list>>.

[#data-collection-data-list]
.What data is collected?
********************************************************************************

* Date/time data
** Date and time of the interaction
* Keyboard data
** Pressed/released keys
* Mouse data
** Mouse position in pixels (assumed to start from (0,0))
** Pressed/released mouse buttons
* Navigation data
** Current URL (protocol and domain only)
** Current scroll position
*** Absolute position in pixels
*** Relative position (measured from the lowest point of the screen)
* User's emotions
** Data got from https://affectiva.com/[Affectiva], an Emotion Analysis engine, by analyzing a snapshot taken with the webcam

********************************************************************************
