all:
	inkscape -z icon.svg -e ../src/extension/assets/icon16.png -w 16
	inkscape -z icon.svg -e ../src/extension/assets/icon32.png -w 32
	inkscape -z icon.svg -e ../src/extension/assets/icon48.png -w 48
	inkscape -z icon.svg -e ../src/extension/assets/icon64.png -w 64
	inkscape -z icon.svg -e ../src/extension/assets/icon128.png -w 128
	convert icon.svg -define icon:auto-resize ../src/server/assets/images/icon.ico
